# Blueprint Render — Odette Panel
# Blueprint Render — Odette Panel
services:
  - type: web
    name: odette-panel
    runtime: python
    plan: free
    buildCommand: python3 -m venv .venv && .venv/bin/pip install -r requirements.txt
    startCommand: .venv/bin/uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DISCORD_CLIENT_ID
        value: "1538362367778488432"
      - key: DISCORD_CLIENT_SECRET
        value: "k3_M1-D50R3nttIJ0PNn7g_bg3QjuWvw"
      - key: DISCORD_REDIRECT_URI
        value: "https://dette-panel-1.onrender.com/callback"
      - key: BOT_OWNER_ID
        value: "545930956721356842"
      - key: SECRET_KEY
        generateValue: true
